# Generated by Django 5.1.6 on 2025-05-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='surname',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='payment',
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
