# Generated by Django 5.1.6 on 2025-05-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_surname_clients_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='password',
        ),
    ]
